### ISSUE TITLE
failed reading file data

### ISSUE THREAD

**Issue by KDAkasa** [cheerss/CrossFormer#20]
Thank you for your contribution to science. I encountered the following issues during the reproduction process:
Traceback (most recent call last):
  File "/tmp/pycharm_project_864/tools/train.py", line 194, in <module>
    main()
  File "/tmp/pycharm_project_864/tools/train.py", line 183, in main
    train_detector(
  File "/tmp/pycharm_project_864/mmdet/apis/train.py", line 185, in train_detector
    runner.load_checkpoint(cfg.load_from)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 349, in load_checkpoint
    return load_checkpoint(
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 627, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 561, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 303, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 323, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/opt/anaconda3/envs/py38/lib/python3.8/site-packages/torch/serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: PytorchStreamReader failed reading file data/2237523104: invalid header or archive is corrupted
May I ask if the weight file of your detection is damaged？

**Comment by cheerss** [comment]
We double-checked the checkpoint files and confirmed they are not damaged. You may wish to re-download the file or check other reasons. If the md5sum is needed for your downloaded file, you can tell me the checkpoint filename you use.
